cdir := ${CURDIR}
TARGET := switchON
PROJ := switchOn
TOP := switchOn
SOURCE := $(cdir)/sitchOn/switchOn.v
FAMILY = ice40
TYPE = hx8k
PACKAGE = cb132

ifeq ($(TARGET), switchOn)
	PCF := switch.pcf
endif
	
include cu.mk
